name: yolo26n_img960_e100

model: yolo26n.pt
model_path: /content/drive/MyDrive/mlops-visdrone/runs/yolo26n_img960_e100/weights/best.pt

data: /content/drive/MyDrive/mlops-visdrone/data/processed/visdrone-yolo/visdrone.yaml

epochs: 60
imgsz: 960
batch: 8
device: 0
workers: 2
# Early stopping
patience: 30

project: /content/drive/MyDrive/mlops-visdrone/mlruns
eval_project: /content/drive/MyDrive/mlops-visdrone/evaluation
eval_name: yolo26n_img960_e100_val
